# -*- coding: utf-8 -*-
"""Streamlit_logistic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUJpVy4z8YGmF9beq52cliAtkIRtEBMO
"""

# app.py

import streamlit as st
import pandas as pd
import joblib

# Load the saved full pipeline logistic model
full_pipeline_model = joblib.load('full_pipeline_logistic_model.pkl')

# Title and description with background image
st.markdown(
    """
    <style>
    .reportview-container {
        background: url("https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQp7xnqk9bEdbVF7Wzmaag8G-ofnkxZyzo1tt_Exm_T6l7Hiw5KqtNeqhpi&s=10");
        background-size: cover;
    }
    </style>
    """,
    unsafe_allow_html=True
)

st.title("Titanic Survival Prediction")
st.write("""
         Enter the details below to predict the survival on the Titanic.
         """)

# Function to get user input
def get_user_input():
    age = st.sidebar.slider("Age", 0.42, 80.0, 29.69, 0.1)
    sibsp = st.sidebar.slider("Siblings/Spouses Aboard", 0, 8, 0, 1)
    parch = st.sidebar.slider("Parents/Children Aboard", 0, 6, 0, 1)
    fare = st.sidebar.slider("Fare", 0.0, 512.3292, 32.20, 0.1)

    user_data = {
        'Age': age,
        'SibSp': sibsp,
        'Parch': parch,
        'Fare': fare
    }

    features = pd.DataFrame(user_data, index=[0])
    return features

# Get user input
user_input = get_user_input()

# Prediction
prediction = full_pipeline_model.predict(user_input)

# Display input data and prediction
st.subheader("User Input")
st.write(user_input)

st.subheader("Prediction")
st.write("Survived" if prediction[0] == 1 else "Did not survive")