# -*- coding: utf-8 -*-
"""Streamlit_logistic_img.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uUJpVy4z8YGmF9beq52cliAtkIRtEBMO
"""

# app.py

import streamlit as st
import pandas as pd
import joblib
import base64

# Load the saved full pipeline logistic model
full_pipeline_model = joblib.load('full_pipeline_logistic_model.pkl')

# Function to load and convert image to Base64
def get_base64_image(image_path):
    with open(image_path, "rb") as img_file:
        return base64.b64encode(img_file.read()).decode()

# Load the image and convert to Base64
base64_image = get_base64_image("titanic-sinking.jpeg")

# Title and description with background image
st.markdown(
    f"""
    <style>
    .reportview-container {{
        background: url("data:image/jpeg;base64,{base64_image}");
        background-size: cover;
    }}
    </style>
    """,
    unsafe_allow_html=True
)

st.title("Titanic Survival Prediction")
st.write("""
         Enter the details below to predict the survival on the Titanic.
         """)

# Function to get user input
def get_user_input():
    age = st.sidebar.slider("Age", 0.42, 80.0, 29.69, 0.1)
    sibsp = st.sidebar.slider("Siblings/Spouses Aboard", 0, 8, 0, 1)
    parch = st.sidebar.slider("Parents/Children Aboard", 0, 6, 0, 1)
    fare = st.sidebar.slider("Fare", 0.0, 512.3292, 32.20, 0.1)

    user_data = {
        'Age': age,
        'SibSp': sibsp,
        'Parch': parch,
        'Fare': fare
    }

    features = pd.DataFrame(user_data, index=[0])
    return features

# Get user input
user_input = get_user_input()

# Prediction
prediction = full_pipeline_model.predict(user_input)

# Display input data and prediction
st.subheader("User Input")
st.write(user_input)

st.subheader("Prediction")
st.write("Survived" if prediction[0] == 1 else "Did not survive")